name: Test Railway CLI install

on:
  push:
    branches: [ main ]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Since this is shiny new project, proceed at your own risk!
      # Also we need contributors for make these config below in the
      # README to work.
      - name: Setup Railway CLI
        uses: MadeByThePinsHub/setup-railway-cli-action@main
      - run: pwd && railway --help
  default-noaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo sh -c "$(curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh)"
      - run: railway --version && railway --help
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install with NPM
        uses: MadeByThePinsHub/setup-railway-cli-action@main
        with:
           npm-mode: true
      - run: pwd && railway --help
  npm-install-noaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir $GITHUB_WORKSPACE/.npm-global
          NPM_CONFIG_PREFIX=$GITHUB_WORKSPACE/.npm-global npm i -g @railway/cli
          export PATH=$GITHUB_WORKSPACE/.npm-global:$PATH
          railway --version
  build-from-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build CLI from source
        uses: MadeByThePinsHub/setup-railway-cli-action@main
        with:
          repo-url: https://github.com/railwayapp/cli
          repo-branch: master
      - run: railway --help
